<?php

/*
 * Admin-managed repeating content. Each list's items live in website_list_items
 * (add / remove / reorder in the admin); `defaults` seed a fresh install and
 * `legacy_keys` tell the migration which numbered website_texts keys to carry
 * values over from. Field names are heading / body / extra; `fields` lists the
 * ones a given list uses and how to label them in the admin.
 */
return [
    'global.trust' => [
        'page' => 'Shared Site Content',
        'section' => 'Trust Bar',
        'label' => 'Trust bar promises',
        'location_hint' => 'The four-item trust bar shown above the footer on most pages.',
        'route_name' => 'home',
        'fields' => ['heading' => 'Promise', 'body' => 'Details'],
        'legacy_keys' => ['heading' => 'global.trust_{i}_title', 'body' => 'global.trust_{i}_detail'],
        'defaults' => [
            ['heading' => '3rd Party Tested', 'body' => 'Every batch, HPLC verified'],
            ['heading' => 'Batch Documented', 'body' => 'Published COA per batch'],
            ['heading' => 'Fast Discreet Shipping', 'body' => 'Ships within 24 hours'],
            ['heading' => 'Independent Labs', 'body' => 'Testing under an ISO/IEC 17025 quality management system'],
        ],
    ],
    'about.stats' => [
        'page' => 'About Page',
        'section' => 'Stats Row',
        'label' => 'Stats row',
        'location_hint' => 'The row of large figures directly under the About page banner.',
        'route_name' => 'about',
        'fields' => ['extra' => 'Figure', 'body' => 'Caption'],
        'legacy_keys' => ['extra' => 'about.stat_{i}_value', 'body' => 'about.stat_{i}_label'],
        'defaults' => [
            ['extra' => 'COA', 'body' => 'Published for every batch'],
            ['extra' => '100%', 'body' => 'Batches third-party tested'],
            ['extra' => '24h', 'body' => 'Typical dispatch time'],
            ['extra' => '0', 'body' => 'Batches shipped without a COA'],
        ],
    ],
    'about.commitments' => [
        'page' => 'About Page',
        'section' => 'Commitments',
        'label' => 'Commitments list',
        'location_hint' => 'Checkmarked list inside "The Commitments" box on the About page.',
        'route_name' => 'about',
        'fields' => ['heading' => 'Heading', 'body' => 'Description'],
        'legacy_keys' => ['heading' => 'about.commitment_{i}_title', 'body' => 'about.commitment_{i}_body'],
        'seed_from' => 'defaults',
        'defaults' => [
            ['heading' => 'Every Batch Tested', 'body' => 'Third-party analytical testing with current batch documentation available through our Lab Reports.'],
            ['heading' => 'Transparent Results', 'body' => 'Current batch testing results are documented and made available through our Lab Reports section.'],
            ['heading' => 'Batch Documentation', 'body' => 'Current batch documentation and corresponding certificates of analysis are available through our Lab Reports section.'],
            ['heading' => 'Honest Pricing', 'body' => 'Volume discounts are applied automatically. No inflated list price to make a fake sale look generous.'],
        ],
    ],
    'about.process' => [
        'page' => 'About Page',
        'section' => 'How It Works',
        'label' => 'Process steps',
        'location_hint' => 'Numbered cards in the "How It Works" section of the About page. Numbers are added automatically.',
        'route_name' => 'about',
        'fields' => ['heading' => 'Step heading', 'body' => 'Step description'],
        'legacy_keys' => ['heading' => 'about.process_{i}_title', 'body' => 'about.process_{i}_body'],
        'seed_from' => 'defaults',
        'defaults' => [
            ['heading' => 'Sourcing', 'body' => 'We work with a small number of vetted synthesis partners operating under documented quality systems. New suppliers go through sample testing long before they get an order.'],
            ['heading' => 'Independent testing', 'body' => 'Samples from each batch are submitted to an independent laboratory for analytical testing, including HPLC analysis where applicable.'],
            ['heading' => 'Review', 'body' => 'Results are reviewed against our ≥95% HPLC purity standard. Current batch documentation and corresponding test results are published in our Lab Reports section.'],
            ['heading' => 'Dispatch', 'body' => 'Vials are packed in plain outer packaging with no product branding, and dispatched typically within 24 hours.'],
        ],
    ],
    'home.why' => [
        'page' => 'Home Page',
        'section' => 'Why Powered Up',
        'label' => 'Trust cards',
        'location_hint' => 'The three cards in the "Why Powered Up" section of the homepage.',
        'route_name' => 'home',
        'fields' => ['extra' => 'Large figure', 'heading' => 'Heading', 'body' => 'Description'],
        'legacy_keys' => ['extra' => 'home.why_{i}_stat', 'heading' => 'home.why_{i}_title', 'body' => 'home.why_{i}_body'],
        'defaults' => [
            ['extra' => '100%', 'heading' => 'Every Batch Tested', 'body' => 'Independent laboratory testing performed under an ISO/IEC 17025 quality management system on every single batch — not a one-off sample from two years ago.'],
            ['extra' => 'Public', 'heading' => 'COA Published First', 'body' => 'The certificate of analysis for your batch number is live on our Lab Reports page before the product goes on sale. Look it up any time.'],
            ['extra' => '24h', 'heading' => 'Discreet Dispatch', 'body' => 'Lyophilised powder is shipped in plain, unbranded packaging within 24 hours of your order clearing.'],
        ],
    ],
    'labs.how' => [
        'page' => 'Lab Reports Page',
        'section' => 'How We Test',
        'label' => 'How We Test cards',
        'location_hint' => 'Numbered cards below the reports table on the Lab Reports page. Numbers are added automatically.',
        'route_name' => 'lab-reports',
        'fields' => ['heading' => 'Heading', 'body' => 'Description'],
        'legacy_keys' => ['heading' => 'labs.how_{i}_title', 'body' => 'labs.how_{i}_body'],
        'defaults' => [
            ['heading' => 'Independent Sampling', 'body' => 'A sealed vial is pulled at random from each production batch and shipped directly to the lab. We never send a prepared sample.'],
            ['heading' => 'Purity, Identity & Quantitation', 'body' => 'Purity, identity and quantitation are established by high performance liquid chromatography (HPLC), verified against the labeled content of each vial.'],
            ['heading' => 'Published Before Sale', 'body' => 'The certificate is uploaded against the batch number here before that batch is released for purchase. If it fails, it does not ship.'],
        ],
    ],
    'contact.faq' => [
        'page' => 'Contact Page',
        'section' => 'FAQ',
        'label' => 'Frequently asked questions',
        'location_hint' => 'The expandable questions under "Common Questions" on the Contact page.',
        'route_name' => 'contact',
        'fields' => ['heading' => 'Question', 'body' => 'Answer'],
        'legacy_keys' => ['heading' => 'contact.faq_{i}_question', 'body' => 'contact.faq_{i}_answer'],
        'defaults' => [
            ['heading' => 'How fast do orders ship?', 'body' => 'Orders placed before 2pm on a business day are packed and dispatched within 24 hours. You will get tracking by email as soon as the label is created.'],
            ['heading' => 'Do you ship internationally?', 'body' => 'We ship to most countries. Customs rules for research chemicals vary, and the buyer is responsible for confirming that import is permitted at their destination.'],
            ['heading' => 'How are the peptides shipped?', 'body' => 'Everything is supplied as lyophilised powder in sealed vials, packed in discreet outer packaging with no product branding on the exterior.'],
            ['heading' => 'Can I get a certificate for my batch?', 'body' => 'Yes. Every batch we sell is third-party tested and published on the lab reports page. Search the batch number printed on your vial label.'],
            ['heading' => 'What is your return policy?', 'body' => 'Because these are research materials, sealed vials cannot be returned once shipped. If an order arrives damaged or incorrect, contact us within 7 days and we will replace it.'],
            ['heading' => 'Do you offer bulk or wholesale pricing?', 'body' => 'Yes. Volume pricing already applies automatically at 3, 5 and 10 vials. For larger laboratory supply agreements, send us your expected monthly volume.'],
        ],
    ],
    'contact.write_tips' => [
        'page' => 'Contact Page',
        'section' => 'Before You Write',
        'label' => 'Before You Write tips',
        'location_hint' => 'Checkmarked lines in the "Before You Write" box on the Contact page.',
        'route_name' => 'contact',
        'fields' => ['body' => 'Tip'],
        'legacy_keys' => ['body' => 'contact.write_tip_{i}'],
        'defaults' => [
            ['body' => 'Include your order reference for anything order related.'],
            ['body' => 'For a certificate, send the batch number from the vial label.'],
            ['body' => 'Wholesale enquiries should include expected monthly volume.'],
        ],
    ],
    'cart.trust' => [
        'page' => 'Cart Page',
        'section' => 'Order Summary',
        'label' => 'Checkmark lines',
        'location_hint' => 'Checkmarked lines under the checkout button in the cart.',
        'route_name' => 'cart',
        'fields' => ['body' => 'Line'],
        'legacy_keys' => ['body' => 'cart.trust_{i}'],
        'defaults' => [
            ['body' => 'Third-party tested, COA per batch'],
            ['body' => 'Discreet, temperature-controlled packing'],
            ['body' => 'Ships within 24 hours'],
        ],
    ],
    'compound_product.trust' => [
        'page' => 'Individual Compound Product Pages',
        'section' => 'Buy Box',
        'label' => 'Checkmark lines',
        'location_hint' => 'Checkmarked lines under the add-to-cart button on individual compound pages.',
        'route_name' => 'shop',
        'fields' => ['body' => 'Line'],
        'legacy_keys' => ['body' => 'compound_product.trust_{i}'],
        'defaults' => [
            ['body' => 'Third-party HPLC tested'],
            ['body' => 'Ships within 24 hours'],
            ['body' => 'Lyophilised powder'],
            ['body' => 'Free shipping over $200'],
        ],
    ],
    'collection_product.trust' => [
        'page' => 'Research Collection Product Pages',
        'section' => 'Buy Box',
        'label' => 'Checkmark lines',
        'location_hint' => 'Checkmarked lines under the add-to-cart button on research collection pages.',
        'route_name' => 'stacks',
        'fields' => ['body' => 'Line'],
        'legacy_keys' => ['body' => 'collection_product.trust_{i}'],
        'defaults' => [
            ['body' => 'Bacteriostatic water included'],
            ['body' => 'COA published per batch'],
            ['body' => 'Ships within 24 hours'],
            ['body' => 'Free shipping over $200'],
        ],
    ],
    'confirmation.steps' => [
        'page' => 'Order Confirmation Page',
        'section' => 'What Happens Next',
        'label' => 'Next steps',
        'location_hint' => 'Numbered steps in the "What Happens Next" box after an order is placed. Numbers are added automatically.',
        'route_name' => null,
        'fields' => ['body' => 'Step'],
        'legacy_keys' => ['body' => 'confirmation.step_{i}'],
        'defaults' => [
            ['body' => 'We confirm payment and pull your batch.'],
            ['body' => 'Packed and dispatched within 24 hours.'],
            ['body' => 'Tracking is emailed as soon as the label is created.'],
        ],
    ],
];
