<?php

$item = static fn (
    string $page,
    string $section,
    string $label,
    string $default,
    string $locationHint,
    ?string $routeName,
    int $sortOrder,
): array => [
    'page' => $page,
    'section' => $section,
    'label' => $label,
    'default' => $default,
    'location_hint' => $locationHint,
    'route_name' => $routeName,
    'sort_order' => $sortOrder,
];

return [
    // Entry acknowledgment gate (shown once per visitor before the site is used).
    'gate.heading' => $item('Shared Site Content', 'Entry Gate', 'Heading', 'RESEARCH USE ONLY', 'Bold line at the top of the entry acknowledgment popup.', 'home', 1),
    'gate.body' => $item('Shared Site Content', 'Entry Gate', 'Body text', 'NOT FOR HUMAN OR VETERINARY USE OR CONSUMPTION. By entering this website, you confirm that you are 21 years of age or older and understand that all products are offered exclusively for laboratory research use.', 'Paragraph in the entry acknowledgment popup.', 'home', 2),
    'gate.button' => $item('Shared Site Content', 'Entry Gate', 'Button', 'I Understand — Enter Site', 'Button that dismisses the entry acknowledgment popup.', 'home', 3),

    // Shared site content.
    'global.meta_description' => $item('Shared Site Content', 'Search & Sharing', 'Default search description', 'Third-party tested research peptides and stack protocols. 99%+ purity, published COA for every batch.', 'Used by search engines and link previews when a page has no custom description.', 'home', 10),
    'global.announcement_title' => $item('Shared Site Content', 'Top Announcement', 'Announcement heading', 'Research Use Only', 'Gold message at the very top of every page.', 'home', 20),
    'global.announcement_detail' => $item('Shared Site Content', 'Top Announcement', 'Announcement details', 'Third-party tested · 99%+ purity · Free shipping over $200', 'Small text beside the gold announcement on larger screens.', 'home', 30),
    'global.nav_shop' => $item('Shared Site Content', 'Main Menu', 'Shop menu item', 'Shop', 'Main navigation on desktop and in the mobile menu.', 'shop', 40),
    'global.nav_collections' => $item('Shared Site Content', 'Main Menu', 'Collections menu item', 'Stacks', 'Main navigation on desktop and in the mobile menu.', 'stacks', 50),
    'global.nav_lab_reports' => $item('Shared Site Content', 'Main Menu', 'Lab reports menu item', 'Lab Reports', 'Main navigation on desktop and in the mobile menu.', 'lab-reports', 60),
    'global.nav_about' => $item('Shared Site Content', 'Main Menu', 'About menu item', 'About Us', 'Main navigation on desktop and in the mobile menu.', 'about', 70),
    'global.nav_contact' => $item('Shared Site Content', 'Main Menu', 'Contact menu item', 'Contact', 'Main navigation on desktop and in the mobile menu.', 'contact', 80),
    'global.footer_description' => $item('Shared Site Content', 'Footer', 'Company description', 'Research-grade peptides with published third-party analysis on every batch. Built for laboratories and researchers who need to trust what is in the vial.', 'Paragraph beside the logo at the bottom of every page.', 'home', 100),
    'global.footer_collections_link' => $item('Shared Site Content', 'Footer', 'Collections link', 'Stack Protocols', 'First link under Shop in the footer.', 'stacks', 110),
    'global.footer_labs_link' => $item('Shared Site Content', 'Footer', 'Lab reports link', 'Lab Reports & COAs', 'First link under Transparency in the footer.', 'lab-reports', 112),
    'global.sort_price_low' => $item('Shared Site Content', 'Product Sorting', 'Low-to-high option', 'Price: Low to High', 'Option in the sort drop-down on the shop and collections pages.', 'shop', 114),
    'global.sort_price_high' => $item('Shared Site Content', 'Product Sorting', 'High-to-low option', 'Price: High to Low', 'Option in the sort drop-down on the shop and collections pages.', 'shop', 116),
    'global.footer_disclaimer_heading' => $item('Shared Site Content', 'Footer Compliance', 'Disclaimer heading', 'RESEARCH USE ONLY.', 'Gold heading in the compliance box at the bottom of every page.', 'home', 120),
    'global.footer_disclaimer' => $item('Shared Site Content', 'Footer Compliance', 'Disclaimer text', 'All products sold by Powered Up Peptides are intended strictly for in-vitro laboratory research and are not for human or veterinary consumption. These products are not drugs, foods, or cosmetics and have not been evaluated by the FDA. Any reference to dosages reflects published third-party literature and is not a recommendation for use in humans. By purchasing, you confirm you are a qualified researcher aged 21 or over.', 'Compliance paragraph at the bottom of every page.', 'home', 130),
    'global.trust_1_title' => $item('Shared Site Content', 'Trust Bar', 'First promise heading', '3rd Party Tested', 'First promise in the four-item trust bar.', 'home', 140),
    'global.trust_1_detail' => $item('Shared Site Content', 'Trust Bar', 'First promise details', 'Every batch, HPLC verified', 'Details below the first trust-bar promise.', 'home', 150),
    'global.trust_2_title' => $item('Shared Site Content', 'Trust Bar', 'Second promise heading', '99%+ Purity', 'Second promise in the four-item trust bar.', 'home', 160),
    'global.trust_2_detail' => $item('Shared Site Content', 'Trust Bar', 'Second promise details', 'Published COA per batch', 'Details below the second trust-bar promise.', 'home', 170),
    'global.trust_3_title' => $item('Shared Site Content', 'Trust Bar', 'Third promise heading', 'Fast Discreet Shipping', 'Third promise in the four-item trust bar.', 'home', 180),
    'global.trust_3_detail' => $item('Shared Site Content', 'Trust Bar', 'Third promise details', 'Ships within 24 hours', 'Details below the third trust-bar promise.', 'home', 190),
    'global.trust_4_title' => $item('Shared Site Content', 'Trust Bar', 'Fourth promise heading', 'Cold Chain Packed', 'Fourth promise in the four-item trust bar.', 'home', 200),
    'global.trust_4_detail' => $item('Shared Site Content', 'Trust Bar', 'Fourth promise details', 'Temperature controlled', 'Details below the fourth trust-bar promise.', 'home', 210),

    // Home page.
    'home.meta_title' => $item('Home Page', 'Search & Sharing', 'Search result title', 'Powered Up Peptides — Research Peptides & Stack Protocols', 'Browser tab, search result, and link-preview title.', 'home', 10),
    'home.hero_eyebrow' => $item('Home Page', 'Top Banner', 'Proof badge', 'Third-Party Tested · 99%+ Purity', 'Small gold badge above the main heading.', 'home', 20),
    'home.hero_title_line_1' => $item('Home Page', 'Top Banner', 'Main heading — first line', 'Power Up Your', 'White first line of the large homepage heading.', 'home', 30),
    'home.hero_title_line_2' => $item('Home Page', 'Top Banner', 'Main heading — gold line', 'Research', 'Gold second line of the large homepage heading.', 'home', 40),
    'home.hero_description' => $item('Home Page', 'Top Banner', 'Introduction', 'Premium research peptides and pre-built stack protocols. Every batch is independently HPLC verified and the certificate of analysis is published before it ships — so you always know exactly what is in the vial.', 'Paragraph below the main homepage heading.', 'home', 50),
    'home.hero_primary_button' => $item('Home Page', 'Top Banner', 'Primary button', 'Shop Stack Protocols', 'Gold button below the homepage introduction.', 'home', 60),
    'home.hero_secondary_button' => $item('Home Page', 'Top Banner', 'Secondary button', 'View Lab Reports', 'Outlined button below the homepage introduction.', 'home', 70),
    'home.collections_eyebrow' => $item('Home Page', 'Collections', 'Section eyebrow', 'Built For Results', 'Small gold text above the collections heading.', 'home', 80),
    'home.collections_title' => $item('Home Page', 'Collections', 'Section heading', 'Stack Protocols', 'Large heading above the collection cards.', 'home', 90),
    'home.collections_description' => $item('Home Page', 'Collections', 'Section description', 'Pre-built systems that pair synergistic compounds with the bacteriostatic water you need. Every stack ships in three protocol tiers — save up to 58% versus buying vials individually.', 'Paragraph above the collection cards.', 'home', 100),
    'home.compounds_eyebrow' => $item('Home Page', 'Individual Compounds', 'Section eyebrow', 'À La Carte', 'Small gold text above the individual compounds heading.', 'home', 110),
    'home.compounds_title' => $item('Home Page', 'Individual Compounds', 'Section heading', 'Individual Compounds', 'Large heading above the individual compound cards.', 'home', 120),
    'home.compounds_description' => $item('Home Page', 'Individual Compounds', 'Section description', 'Building your own protocol? Every compound is available on its own with quantity-break pricing — the more vials, the lower the unit cost.', 'Paragraph above the individual compound cards.', 'home', 130),
    'home.why_eyebrow' => $item('Home Page', 'Why Powered Up', 'Section eyebrow', 'Why Powered Up', 'Small gold text above the trust section.', 'home', 140),
    'home.why_title' => $item('Home Page', 'Why Powered Up', 'Section heading', 'No Guessing. Ever.', 'Large heading above the three trust cards.', 'home', 150),
    'home.why_description' => $item('Home Page', 'Why Powered Up', 'Section description', 'Most suppliers ask you to take their word for it. We publish the receipts.', 'Short paragraph above the three trust cards.', 'home', 160),
    'home.why_1_stat' => $item('Home Page', 'Why Powered Up', 'Card 1 figure', '100%', 'Large accent figure on the first trust card.', 'home', 161),
    'home.why_1_title' => $item('Home Page', 'Why Powered Up', 'Card 1 heading', 'Every Batch Tested', 'Heading of the first trust card.', 'home', 162),
    'home.why_1_body' => $item('Home Page', 'Why Powered Up', 'Card 1 text', 'Independent ISO-accredited HPLC analysis on every single batch — not a one-off sample from two years ago.', 'Description on the first trust card.', 'home', 163),
    'home.why_2_stat' => $item('Home Page', 'Why Powered Up', 'Card 2 figure', 'Public', 'Large accent figure on the second trust card.', 'home', 164),
    'home.why_2_title' => $item('Home Page', 'Why Powered Up', 'Card 2 heading', 'COA Published First', 'Heading of the second trust card.', 'home', 165),
    'home.why_2_body' => $item('Home Page', 'Why Powered Up', 'Card 2 text', 'The certificate of analysis for your batch number is live on our Lab Reports page before the product goes on sale. Look it up any time.', 'Description on the second trust card.', 'home', 166),
    'home.why_3_stat' => $item('Home Page', 'Why Powered Up', 'Card 3 figure', '24h', 'Large accent figure on the third trust card.', 'home', 167),
    'home.why_3_title' => $item('Home Page', 'Why Powered Up', 'Card 3 heading', 'Discreet Dispatch', 'Heading of the third trust card.', 'home', 168),
    'home.why_3_body' => $item('Home Page', 'Why Powered Up', 'Card 3 text', 'Lyophilised powder is shipped in plain, unbranded packaging within 24 hours of your order clearing.', 'Description on the third trust card.', 'home', 169),
    'home.closing_title' => $item('Home Page', 'Bottom Call To Action', 'Heading', 'Ready To Power Up?', 'Large heading near the bottom of the homepage.', 'home', 170),
    'home.closing_description' => $item('Home Page', 'Bottom Call To Action', 'Description', 'Start with a stack protocol built around your research goal, or browse the full compound library and build your own.', 'Paragraph in the bottom call-to-action box.', 'home', 180),
    'home.closing_primary_button' => $item('Home Page', 'Bottom Call To Action', 'Primary button', 'Shop Stack Protocols', 'Gold button in the bottom call-to-action box.', 'home', 190),

    // Shop page.
    'shop.meta_description' => $item('Shop Page', 'Search & Sharing', 'Search description', 'Individual research peptides with published third-party analysis and quantity-break pricing on every vial.', 'Search result and link-preview description for the Shop page.', 'shop', 10),
    'shop.hero_eyebrow' => $item('Shop Page', 'Top Banner', 'Eyebrow', 'Individual Compounds', 'Small gold heading at the top of the Shop page.', 'shop', 20),
    'shop.hero_title' => $item('Shop Page', 'Top Banner', 'Main heading', 'Shop Compounds', 'Large heading when no product category is selected.', 'shop', 30),
    'shop.hero_description' => $item('Shop Page', 'Top Banner', 'Introduction', 'Single vials for researchers building their own protocol. Every compound is third-party tested with the certificate published against its batch number, and unit prices drop automatically as quantity goes up.', 'Paragraph under the Shop page heading.', 'shop', 40),
    'shop.collections_link' => $item('Shop Page', 'Top Banner', 'Collections link', 'Looking for complete protocols? Browse stacks →', 'Gold link below the Shop introduction.', 'shop', 50),
    'shop.cross_sell_title' => $item('Shop Page', 'Bottom Call To Action', 'Heading', 'Rather Not Build It Yourself?', 'Large heading in the bottom collection callout.', 'shop', 60),
    'shop.cross_sell_description' => $item('Shop Page', 'Bottom Call To Action', 'Description', 'Our stack protocols pair these compounds into complete programmes with a set supply length, so you do not have to work out the combination.', 'Paragraph in the bottom collection callout.', 'shop', 70),
    'shop.cross_sell_button' => $item('Shop Page', 'Bottom Call To Action', 'Button', 'View Stack Protocols', 'Gold button in the bottom collection callout.', 'shop', 80),

    // Research collections page (currently /stacks).
    'collections.meta_title' => $item('Research Collections Page', 'Search & Sharing', 'Search result title', 'Stack Protocols — Powered Up Peptides', 'Browser tab, search result, and link-preview title when no category is selected.', 'stacks', 10),
    'collections.meta_description' => $item('Research Collections Page', 'Search & Sharing', 'Search description', 'Complete research peptide protocols. Each stack pairs proven compounds into a programme with a set supply length and published lab results.', 'Search result and link-preview description.', 'stacks', 20),
    'collections.breadcrumb' => $item('Research Collections Page', 'Top Banner', 'Breadcrumb label', 'Stacks', 'Small page name beside Home at the top.', 'stacks', 30),
    'collections.hero_eyebrow' => $item('Research Collections Page', 'Top Banner', 'Eyebrow', 'Complete Protocols', 'Small gold heading above the main page title.', 'stacks', 40),
    'collections.hero_title' => $item('Research Collections Page', 'Top Banner', 'Main heading', 'Stack Protocols', 'Large title in the page banner when no category is selected.', 'stacks', 50),
    'collections.hero_description' => $item('Research Collections Page', 'Top Banner', 'Introduction', 'Every stack pairs compounds that work together into one programme, with a fixed supply length and a single price. Pick the goal, pick the duration, and everything arrives in one cold chain shipment.', 'Paragraph below the main page title.', 'stacks', 60),
    'collections.shop_link' => $item('Research Collections Page', 'Top Banner', 'Single-vials link', 'Prefer single vials? Shop compounds →', 'Gold link below the introduction.', 'stacks', 70),
    'collections.all_filter' => $item('Research Collections Page', 'Product List', 'All-items filter', 'All Protocols', 'First filter button above the collection cards.', 'stacks', 80),

    // Lab reports page.
    'labs.meta_title' => $item('Lab Reports Page', 'Search & Sharing', 'Search result title', 'Lab Reports & Certificates of Analysis — Powered Up Peptides', 'Browser tab, search result, and link-preview title.', 'lab-reports', 10),
    'labs.hero_title' => $item('Lab Reports Page', 'Top Banner', 'Main heading', 'Lab Reports', 'Large title at the top of the page.', 'lab-reports', 20),
    'labs.hero_description' => $item('Lab Reports Page', 'Top Banner', 'Introduction', 'Every batch we sell receives independent purity, identity and quantitation testing (HPLC) before it goes on sale. Look up any batch number printed on your vial to see its certificate of analysis.', 'Paragraph under the main page heading.', 'lab-reports', 30),
    'labs.search_placeholder' => $item('Lab Reports Page', 'Batch Search', 'Search box placeholder', 'Enter batch number or product name', 'Faint instruction inside the batch search box.', 'lab-reports', 40),
    'labs.search_button' => $item('Lab Reports Page', 'Batch Search', 'Search button', 'Look Up', 'Gold button beside the batch search box.', 'lab-reports', 50),
    'labs.pending_label' => $item('Lab Reports Page', 'Reports Table', 'Awaiting-documentation label', 'Documentation Pending', 'Shown for a product whose current certificate has not been published yet.', 'lab-reports', 60),
    'labs.testing_label' => $item('Lab Reports Page', 'Reports Table', 'Testing-in-progress label', 'Additional Testing in Progress', 'Status shown for a product undergoing additional laboratory testing.', 'lab-reports', 62),
    'labs.testing_note' => $item('Lab Reports Page', 'Reports Table', 'Testing-in-progress note', 'Updated analytical documentation will be published upon completion of testing.', 'Explanation shown with the testing-in-progress status.', 'lab-reports', 64),
    'labs.table_note' => $item('Lab Reports Page', 'Reports Table', 'Note below reports', 'Certificates of analysis are issued by the independent laboratory named on each row for the exact batch shown. Batches undergoing additional testing are published once updated documentation is available.', 'Small explanatory note directly below the reports table.', 'lab-reports', 70),
    'labs.empty_title' => $item('Lab Reports Page', 'No-Match Message', 'Heading', 'No matching batch', 'Heading shown when a batch search finds nothing.', 'lab-reports', 72),
    'labs.empty_description' => $item('Lab Reports Page', 'No-Match Message', 'Description', 'Check the number printed on your vial label, or contact us and we will send the certificate directly.', 'Text under the no-match heading.', 'lab-reports', 74),
    'labs.how_1_title' => $item('Lab Reports Page', 'How We Test', 'Card 1 heading', 'Independent Sampling', 'Heading of the first How We Test card.', 'lab-reports', 82),
    'labs.how_1_body' => $item('Lab Reports Page', 'How We Test', 'Card 1 text', 'A sealed vial is pulled at random from each production batch and shipped directly to the lab. We never send a prepared sample.', 'Description on the first How We Test card.', 'lab-reports', 83),
    'labs.how_2_title' => $item('Lab Reports Page', 'How We Test', 'Card 2 heading', 'Purity, Identity & Quantitation', 'Heading of the second How We Test card.', 'lab-reports', 84),
    'labs.how_2_body' => $item('Lab Reports Page', 'How We Test', 'Card 2 text', 'Purity, identity and quantitation are established by high performance liquid chromatography (HPLC), verified against the labeled content of each vial.', 'Description on the second How We Test card.', 'lab-reports', 85),
    'labs.how_3_title' => $item('Lab Reports Page', 'How We Test', 'Card 3 heading', 'Published Before Sale', 'Heading of the third How We Test card.', 'lab-reports', 86),
    'labs.how_3_body' => $item('Lab Reports Page', 'How We Test', 'Card 3 text', 'The certificate is uploaded against the batch number here before that batch is released for purchase. If it fails, it does not ship.', 'Description on the third How We Test card.', 'lab-reports', 87),

    // About page.
    'about.meta_description' => $item('About Page', 'Search & Sharing', 'Search description', 'Who we are, how we source and test our research peptides, and the standards every batch has to clear before it ships.', 'Search result and link-preview description.', 'about', 10),
    'about.hero_eyebrow' => $item('About Page', 'Top Banner', 'Eyebrow', 'Our Standard', 'Small gold heading above the main title.', 'about', 20),
    'about.hero_title' => $item('About Page', 'Top Banner', 'Main heading', 'Know Exactly What Is In The Vial', 'Large heading at the top of the About page.', 'about', 30),
    'about.hero_description' => $item('About Page', 'Top Banner', 'Introduction', 'Powered Up Peptides exists because too much of this market asks researchers to take purity on faith. We publish the analysis for every batch we sell, so you never have to.', 'Paragraph below the main About heading.', 'about', 40),
    'about.story_eyebrow' => $item('About Page', 'Our Story', 'Eyebrow', 'Why We Started', 'Small gold heading above the company story.', 'about', 50),
    'about.story_title' => $item('About Page', 'Our Story', 'Heading', 'Built Out Of Frustration', 'Large heading above the company story.', 'about', 60),
    'about.story_paragraph_1' => $item('About Page', 'Our Story', 'First paragraph', 'Anyone who has sourced research peptides knows the routine. A vendor claims 99% purity. There is no certificate, or there is one certificate from two years ago covering a batch you did not receive. You are left running your own verification before you can even begin the work you actually planned.', 'First paragraph in the Why We Started section.', 'about', 70),
    'about.story_paragraph_2' => $item('About Page', 'Our Story', 'Second paragraph', 'We built Powered Up Peptides around the opposite default. Every batch is sent to an independent lab for HPLC purity, identity and quantitation analysis before it is listed. That report is published against the batch number printed on your vial, and it stays public whether the result flatters us or not.', 'Second paragraph in the Why We Started section.', 'about', 80),
    'about.story_paragraph_3' => $item('About Page', 'Our Story', 'Third paragraph', 'If a batch does not clear our purity threshold, it does not get sold. It is a simple rule, and it is the entire reason this company exists.', 'Third paragraph in the Why We Started section.', 'about', 90),
    'about.compliance_eyebrow' => $item('About Page', 'Compliance', 'Eyebrow', 'Where We Draw The Line', 'Small gold heading above the compliance statement.', 'about', 100),
    'about.compliance_title' => $item('About Page', 'Compliance', 'Heading', 'Research Use Only', 'Large heading above the compliance statement.', 'about', 110),
    'about.compliance_paragraph_1' => $item('About Page', 'Compliance', 'First paragraph', 'Everything we sell is supplied strictly for in-vitro laboratory research. Our products are not drugs, foods or cosmetics, they have not been evaluated by the FDA, and they are not for human or veterinary consumption.', 'First paragraph in the compliance box.', 'about', 120),
    'about.compliance_paragraph_2' => $item('About Page', 'Compliance', 'Second paragraph', 'We do not provide dosing protocols, medical guidance or advice on administration, and we will not do so if asked. Where our product pages cite figures from published literature, that is a reference to the research record, not a recommendation.', 'Second paragraph in the compliance box.', 'about', 130),
    'about.compliance_paragraph_3' => $item('About Page', 'Compliance', 'Third paragraph', 'By ordering, you confirm you are a qualified researcher aged 21 or over and that you are responsible for compliance with the regulations that apply where you are.', 'Final paragraph in the compliance box.', 'about', 140),
    'about.meta_title' => $item('About Page', 'Search & Sharing', 'Browser tab title', 'About — Powered Up Peptides', 'Browser tab, search result, and link-preview title.', 'about', 5),
    'about.stat_1_value' => $item('About Page', 'Stats Row', 'First stat value', 'COA', 'Large gold figure in the first stats tile.', 'about', 12),
    'about.stat_1_label' => $item('About Page', 'Stats Row', 'First stat label', 'Published for every batch', 'Caption under the first stats tile.', 'about', 13),
    'about.stat_2_value' => $item('About Page', 'Stats Row', 'Second stat value', '100%', 'Large gold figure in the second stats tile.', 'about', 14),
    'about.stat_2_label' => $item('About Page', 'Stats Row', 'Second stat label', 'Batches third-party tested', 'Caption under the second stats tile.', 'about', 15),
    'about.stat_3_value' => $item('About Page', 'Stats Row', 'Third stat value', '24h', 'Large gold figure in the third stats tile.', 'about', 16),
    'about.stat_3_label' => $item('About Page', 'Stats Row', 'Third stat label', 'Typical dispatch time', 'Caption under the third stats tile.', 'about', 17),
    'about.stat_4_value' => $item('About Page', 'Stats Row', 'Fourth stat value', '0', 'Large gold figure in the fourth stats tile.', 'about', 18),
    'about.stat_4_label' => $item('About Page', 'Stats Row', 'Fourth stat label', 'Batches shipped without a COA', 'Caption under the fourth stats tile.', 'about', 19),
    'about.commitments_eyebrow' => $item('About Page', 'Commitments', 'Box heading', 'The Commitments', 'Gold label at the top of the commitments box.', 'about', 82),
    'about.commitment_1_title' => $item('About Page', 'Commitments', 'First commitment heading', 'Every batch tested', 'Bold line of the first commitment.', 'about', 83),
    'about.commitment_1_body' => $item('About Page', 'Commitments', 'First commitment text', 'Independent HPLC purity, identity and quantitation analysis, published against the batch number on your vial.', 'Description of the first commitment.', 'about', 84),
    'about.commitment_2_title' => $item('About Page', 'Commitments', 'Second commitment heading', 'No hidden failures', 'Bold line of the second commitment.', 'about', 85),
    'about.commitment_2_body' => $item('About Page', 'Commitments', 'Second commitment text', 'Reports stay public regardless of the result. Batches under threshold are destroyed, not discounted.', 'Description of the second commitment.', 'about', 86),
    'about.commitment_3_title' => $item('About Page', 'Commitments', 'Third commitment heading', 'Batch documentation', 'Bold line of the third commitment.', 'about', 87),
    'about.commitment_3_body' => $item('About Page', 'Commitments', 'Third commitment text', 'Lyophilised and sealed, with the certificate of analysis published against the batch number.', 'Description of the third commitment.', 'about', 88),
    'about.commitment_4_title' => $item('About Page', 'Commitments', 'Fourth commitment heading', 'Honest pricing', 'Bold line of the fourth commitment.', 'about', 89),
    'about.commitment_4_body' => $item('About Page', 'Commitments', 'Fourth commitment text', 'Volume discounts are applied automatically. No inflated list price to make a fake sale look generous.', 'Description of the fourth commitment.', 'about', 90),
    'about.process_eyebrow' => $item('About Page', 'How It Works', 'Section eyebrow', 'How It Works', 'Small label above the process section heading.', 'about', 91),
    'about.process_title' => $item('About Page', 'How It Works', 'Section heading', 'From Synthesis To Your Bench', 'Large heading above the four process cards. The last three words are shown in the accent colour.', 'about', 92),
    'about.process_subtitle' => $item('About Page', 'How It Works', 'Section description', 'Four checkpoints, and a batch has to clear all of them.', 'Line under the process section heading.', 'about', 93),
    'about.process_1_title' => $item('About Page', 'How It Works', 'Step 1 heading', 'Sourcing', 'Heading of the first process card.', 'about', 94),
    'about.process_1_body' => $item('About Page', 'How It Works', 'Step 1 text', 'We work with a small number of vetted synthesis partners operating under documented quality systems. New suppliers go through sample testing long before they get an order.', 'Description in the first process card.', 'about', 95),
    'about.process_2_title' => $item('About Page', 'How It Works', 'Step 2 heading', 'Independent testing', 'Heading of the second process card.', 'about', 96),
    'about.process_2_body' => $item('About Page', 'How It Works', 'Step 2 text', 'Every batch goes to a third-party lab, where HPLC analysis establishes purity, identity and quantitation against the labeled content.', 'Description in the second process card.', 'about', 97),
    'about.process_3_title' => $item('About Page', 'How It Works', 'Step 3 heading', 'Review', 'Heading of the third process card.', 'about', 98),
    'about.process_3_body' => $item('About Page', 'How It Works', 'Step 3 text', 'Results are checked against our 99% threshold. Anything that falls short is rejected outright. Passing batches get their COA published.', 'Description in the third process card.', 'about', 99),
    'about.process_4_title' => $item('About Page', 'How It Works', 'Step 4 heading', 'Dispatch', 'Heading of the fourth process card.', 'about', 100),
    'about.process_4_body' => $item('About Page', 'How It Works', 'Step 4 text', 'Vials are packed in plain outer packaging with no product branding, and dispatched typically within 24 hours.', 'Description in the fourth process card.', 'about', 101),
    'about.cta_title' => $item('About Page', 'Closing Call-To-Action', 'Heading', 'Check Us Before You Buy', 'Large heading in the closing banner. The last three words are shown in the accent colour.', 'about', 120),
    'about.cta_description' => $item('About Page', 'Closing Call-To-Action', 'Description', 'Do not take our word for any of this. Pull a batch certificate and read the numbers yourself.', 'Paragraph under the closing banner heading.', 'about', 122),

    // Contact page.
    'contact.meta_description' => $item('Contact Page', 'Search & Sharing', 'Search description', 'Questions about an order, a protocol or a batch certificate? Talk to the Powered Up Peptides team.', 'Search result and link-preview description.', 'contact', 10),
    'contact.hero_title' => $item('Contact Page', 'Top Banner', 'Main heading', 'Talk To Us', 'Large heading at the top of the Contact page.', 'contact', 20),
    'contact.hero_description' => $item('Contact Page', 'Top Banner', 'Introduction', 'Order issues, batch certificates, protocol questions or bulk enquiries — a real person reads every message and replies within one business day.', 'Paragraph below the main Contact heading.', 'contact', 30),
    'contact.form_disclaimer' => $item('Contact Page', 'Message Form', 'Advice disclaimer', 'We cannot provide dosing, medical or veterinary advice. All products are supplied strictly for laboratory research use.', 'Small compliance note below the Send Message button.', 'contact', 40),
    'contact.protocol_help_title' => $item('Contact Page', 'Faster Answers', 'Collection-help link heading', 'Not sure which protocol?', 'Third shortcut card in the Faster Answers box.', 'contact', 50),
    'contact.protocol_help_description' => $item('Contact Page', 'Faster Answers', 'Collection-help link description', 'Every stack lists its goal, components and supply length.', 'Description in the third Faster Answers shortcut card.', 'contact', 60),
    'contact.meta_title' => $item('Contact Page', 'Search & Sharing', 'Browser tab title', 'Contact — Powered Up Peptides', 'Browser tab, search result, and link-preview title.', 'contact', 5),
    'contact.form_subject_label' => $item('Contact Page', 'Message Form', 'Topic field label', 'What is it about?', 'Label above the topic drop-down in the message form.', 'contact', 35),
    'contact.certificate_help_title' => $item('Contact Page', 'Faster Answers', 'Certificate link heading', 'Looking for a certificate?', 'First shortcut card in the Faster Answers box.', 'contact', 42),
    'contact.certificate_help_description' => $item('Contact Page', 'Faster Answers', 'Certificate link description', 'Search any batch number on the lab reports page.', 'Description in the first Faster Answers shortcut card.', 'contact', 44),
    'contact.account_help_description' => $item('Contact Page', 'Faster Answers', 'Order link description', 'Order history and status live in your account.', 'Description in the second Faster Answers shortcut card.', 'contact', 46),
    'contact.response_email' => $item('Contact Page', 'Response Times', 'Email response time', 'Within 1 business day', 'Value shown beside "Email" in the Response Times box.', 'contact', 62),
    'contact.write_tip_1' => $item('Contact Page', 'Before You Write', 'First tip', 'Include your order reference for anything order related.', 'First checklist line in the Before You Write box.', 'contact', 64),
    'contact.write_tip_2' => $item('Contact Page', 'Before You Write', 'Second tip', 'For a certificate, send the batch number from the vial label.', 'Second checklist line in the Before You Write box.', 'contact', 66),
    'contact.write_tip_3' => $item('Contact Page', 'Before You Write', 'Third tip', 'Wholesale enquiries should include expected monthly volume.', 'Third checklist line in the Before You Write box.', 'contact', 68),
    'contact.faq_1_question' => $item('Contact Page', 'FAQ', 'Question 1', 'How fast do orders ship?', 'First question in the FAQ accordion.', 'contact', 70),
    'contact.faq_1_answer' => $item('Contact Page', 'FAQ', 'Answer 1', 'Orders placed before 2pm on a business day are packed and dispatched within 24 hours. You will get tracking by email as soon as the label is created.', 'Answer to the first FAQ question.', 'contact', 71),
    'contact.faq_2_question' => $item('Contact Page', 'FAQ', 'Question 2', 'Do you ship internationally?', 'Second question in the FAQ accordion.', 'contact', 72),
    'contact.faq_2_answer' => $item('Contact Page', 'FAQ', 'Answer 2', 'We ship to most countries. Customs rules for research chemicals vary, and the buyer is responsible for confirming that import is permitted at their destination.', 'Answer to the second FAQ question.', 'contact', 73),
    'contact.faq_3_question' => $item('Contact Page', 'FAQ', 'Question 3', 'How are the peptides shipped?', 'Third question in the FAQ accordion.', 'contact', 74),
    'contact.faq_3_answer' => $item('Contact Page', 'FAQ', 'Answer 3', 'Everything is supplied as lyophilised powder in sealed vials, packed in discreet outer packaging with no product branding on the exterior.', 'Answer to the third FAQ question.', 'contact', 75),
    'contact.faq_4_question' => $item('Contact Page', 'FAQ', 'Question 4', 'Can I get a certificate for my batch?', 'Fourth question in the FAQ accordion.', 'contact', 76),
    'contact.faq_4_answer' => $item('Contact Page', 'FAQ', 'Answer 4', 'Yes. Every batch we sell is third-party tested and published on the lab reports page. Search the batch number printed on your vial label.', 'Answer to the fourth FAQ question.', 'contact', 77),
    'contact.faq_5_question' => $item('Contact Page', 'FAQ', 'Question 5', 'What is your return policy?', 'Fifth question in the FAQ accordion.', 'contact', 78),
    'contact.faq_5_answer' => $item('Contact Page', 'FAQ', 'Answer 5', 'Because these are research materials, sealed vials cannot be returned once shipped. If an order arrives damaged or incorrect, contact us within 7 days and we will replace it.', 'Answer to the fifth FAQ question.', 'contact', 79),
    'contact.faq_6_question' => $item('Contact Page', 'FAQ', 'Question 6', 'Do you offer bulk or wholesale pricing?', 'Sixth question in the FAQ accordion.', 'contact', 80),
    'contact.faq_6_answer' => $item('Contact Page', 'FAQ', 'Answer 6', 'Yes. Volume pricing already applies automatically at 3, 5 and 10 vials. For larger laboratory supply agreements, send us your expected monthly volume.', 'Answer to the sixth FAQ question.', 'contact', 81),

    // Cart and checkout compliance text.
    'cart.meta_title' => $item('Cart Page', 'Search & Sharing', 'Browser tab title', 'Your Cart — Powered Up Peptides', 'Browser tab title of the cart page.', 'cart', 2),
    'cart.empty_title' => $item('Cart Page', 'Empty Cart', 'Empty-cart heading', 'Nothing in here yet', 'Heading shown when the shopping cart is empty.', 'cart', 8),
    'cart.empty_description' => $item('Cart Page', 'Empty Cart', 'Empty-cart description', 'Start with a stack protocol built around your research goal, or browse the compound library and build your own.', 'Paragraph shown when the shopping cart is empty.', 'cart', 10),
    'cart.shipping_unlocked' => $item('Cart Page', 'Order Summary', 'Free-shipping unlocked message', 'Free standard shipping unlocked.', 'Gold message when the cart qualifies for free shipping.', 'cart', 30),
    'cart.trust_1' => $item('Cart Page', 'Order Summary', 'First checkmark line', 'Third-party tested, COA per batch', 'First checkmark under the checkout button.', 'cart', 50),
    'cart.trust_2' => $item('Cart Page', 'Order Summary', 'Second checkmark line', 'Discreet, temperature-controlled packing', 'Second checkmark under the checkout button.', 'cart', 52),
    'cart.trust_3' => $item('Cart Page', 'Order Summary', 'Third checkmark line', 'Ships within 24 hours', 'Third checkmark under the checkout button.', 'cart', 54),
    'cart.empty_collections_button' => $item('Cart Page', 'Empty Cart', 'Collections button', 'Shop Stack Protocols', 'Gold button shown when the shopping cart is empty.', 'cart', 20),
    'cart.disclaimer_heading' => $item('Cart Page', 'Checkout Disclaimer', 'Disclaimer heading', 'Research-use disclaimer', 'Gold heading above the required acceptance checkbox.', 'cart', 30),
    'cart.disclaimer_text' => $item('Cart Page', 'Checkout Disclaimer', 'Required acceptance text', 'I confirm that I am a qualified researcher aged 21 or over and that these products are strictly for in-vitro laboratory research only. They are not for human or veterinary consumption, diagnostic use, or therapeutic use.', 'Text beside the required checkbox before checkout.', 'cart', 40),
    'cart.disclaimer_button' => $item('Cart Page', 'Checkout Disclaimer', 'Proceed button', 'Accept & Proceed To Checkout', 'Checkout button directly below the required disclaimer.', 'cart', 50),
    'checkout.meta_title' => $item('Checkout Page', 'Search & Sharing', 'Browser tab title', 'Checkout — Powered Up Peptides', 'Browser tab title of the checkout page.', 'checkout', 2),
    'checkout.error_heading' => $item('Checkout Page', 'Validation', 'Error box heading', 'Please fix the following:', 'Heading of the red error box when the form has problems.', 'checkout', 5),
    'checkout.disclaimer_text' => $item('Checkout Page', 'Compliance', 'Final confirmation text', 'I confirm I am a qualified researcher aged 21 or over, and that these products will be used strictly for in-vitro laboratory research. They are not for human or veterinary consumption, and not for diagnostic or therapeutic use.', 'Text beside the compliance checkbox on checkout.', 'checkout', 10),
    'checkout.payment_note' => $item('Checkout Page', 'Payment', 'Note under the place-order button', 'No payment is collected online. Your order is placed as awaiting payment, and we will contact you with payment instructions.', 'Small note under the place-order button.', 'checkout', 20),
    'confirmation.intro' => $item('Order Confirmation Page', 'Header', 'Thanks line', 'your order is in.', 'Completes the sentence "Thanks[, name] — …" at the top of the order confirmation.', null, 10),
    'confirmation.email_note' => $item('Order Confirmation Page', 'Header', 'Email note', 'A confirmation has been sent to', 'Shown before the customer\'s email address.', null, 20),
    'confirmation.steps_title' => $item('Order Confirmation Page', 'What Happens Next', 'Box heading', 'What Happens Next', 'Heading of the what-happens-next box.', null, 30),
    'confirmation.step_1' => $item('Order Confirmation Page', 'What Happens Next', 'Step 1', 'We confirm payment and pull your batch.', 'First step in the what-happens-next list.', null, 32),
    'confirmation.step_2' => $item('Order Confirmation Page', 'What Happens Next', 'Step 2', 'Packed and dispatched within 24 hours.', 'Second step in the what-happens-next list.', null, 34),
    'confirmation.step_3' => $item('Order Confirmation Page', 'What Happens Next', 'Step 3', 'Tracking is emailed as soon as the label is created.', 'Third step in the what-happens-next list.', null, 36),
    'confirmation.lab_reports_button' => $item('Order Confirmation Page', 'Footer Buttons', 'Lab reports button', 'View Batch Lab Reports', 'Outlined button at the bottom of the confirmation page.', null, 40),

    // Text shared by all research-collection product pages.
    'collection_product.breadcrumb' => $item('Research Collection Product Pages', 'Top Banner', 'Collections breadcrumb', 'Stack Protocols', 'Small link between Home and the product name.', 'stacks', 10),
    'collection_product.choose_heading' => $item('Research Collection Product Pages', 'Buying Options', 'Option selector heading', 'Choose Your Protocol', 'Heading immediately above the collection options.', 'stacks', 20),
    'collection_product.choose_help' => $item('Research Collection Product Pages', 'Buying Options', 'Option selector help', 'Longer supply = lower cost per vial', 'Small help text beside the option selector heading.', 'stacks', 30),
    'collection_product.add_button' => $item('Research Collection Product Pages', 'Buying Options', 'Add-to-cart button', 'Add Protocol To Cart', 'Large button below the collection options.', 'stacks', 40),
    'collection_product.included_eyebrow' => $item('Research Collection Product Pages', 'What Is Included', 'Section eyebrow', 'Inside The Box', 'Small label above the included-items heading.', 'stacks', 50),
    'collection_product.included_title' => $item('Research Collection Product Pages', 'What Is Included', 'Section heading', 'What’s Included', 'Large heading above the included-items table.', 'stacks', 60),
    'collection_product.included_description' => $item('Research Collection Product Pages', 'What Is Included', 'Section description', 'Vial counts below are shown per protocol tier. Every tier includes the bacteriostatic water required to reconstitute the full protocol.', 'Paragraph above the included-items table.', 'stacks', 70),
    'collection_product.table_compound_heading' => $item('Research Collection Product Pages', 'What Is Included', 'Table heading — item column', 'Compound', 'First column heading of the included-items table.', 'stacks', 72),
    'collection_product.table_details_heading' => $item('Research Collection Product Pages', 'What Is Included', 'Table heading — details column', 'Product Details', 'Second column heading of the included-items table.', 'stacks', 74),
    'collection_product.compounds_eyebrow' => $item('Research Collection Product Pages', 'Included Compounds', 'Section eyebrow', 'The Compounds', 'Small label above the included compound cards.', 'stacks', 120),
    'collection_product.compounds_title' => $item('Research Collection Product Pages', 'Included Compounds', 'Section heading', 'Every Vial, Documented', 'Large heading above the included compound cards.', 'stacks', 130),
    'collection_product.compounds_description' => $item('Research Collection Product Pages', 'Included Compounds', 'Section description', 'Each compound in this protocol has its own product page with research background, storage guidance, and the batch certificate of analysis.', 'Paragraph above the included compound cards.', 'stacks', 140),
    'collection_product.lab_eyebrow' => $item('Research Collection Product Pages', 'Lab Results', 'Section eyebrow', 'Transparency', 'Small label above the batch lab results heading.', 'stacks', 145),
    'collection_product.lab_title' => $item('Research Collection Product Pages', 'Lab Results', 'Section heading', 'Batch Lab Results', 'Large heading above the batch results table. The last two words are shown in the accent colour.', 'stacks', 148),
    'collection_product.lab_description' => $item('Research Collection Product Pages', 'Lab Results', 'Section description', 'Independent third-party analysis for the exact batches included in this protocol.', 'Paragraph above product-level batch results.', 'stacks', 150),
    'collection_product.other_title' => $item('Research Collection Product Pages', 'Related Collections', 'Section heading', 'Other Protocols', 'Heading above other research collection cards.', 'stacks', 160),
    'collection_product.trust_1' => $item('Research Collection Product Pages', 'Buy Box', 'First checkmark line', 'Bacteriostatic water included', 'First checkmark under the add-to-cart button.', 'stacks', 170),
    'collection_product.trust_2' => $item('Research Collection Product Pages', 'Buy Box', 'Second checkmark line', 'COA published per batch', 'Second checkmark under the add-to-cart button.', 'stacks', 172),
    'collection_product.trust_3' => $item('Research Collection Product Pages', 'Buy Box', 'Third checkmark line', 'Ships within 24 hours', 'Third checkmark under the add-to-cart button.', 'stacks', 174),
    'collection_product.trust_4' => $item('Research Collection Product Pages', 'Buy Box', 'Fourth checkmark line', 'Free shipping over $200', 'Fourth checkmark under the add-to-cart button. Display text only — the actual free-shipping threshold is configured separately by your developer.', 'stacks', 176),
    'collection_product.retail_value_label' => $item('Research Collection Product Pages', 'Included Table', 'Retail value label', 'Retail value if bought separately', 'Label above the crossed-out retail total in the included-items table.', 'stacks', 178),

    // Text shared by all individual compound product pages.
    'compound_product.quantity_heading' => $item('Individual Compound Product Pages', 'Buying Options', 'Quantity selector heading', 'Choose Quantity', 'Heading immediately above quantity choices.', 'shop', 10),
    'compound_product.quantity_help' => $item('Individual Compound Product Pages', 'Buying Options', 'Quantity selector help', 'Unit price drops with volume', 'Small help text beside the quantity selector heading.', 'shop', 20),
    'compound_product.add_button' => $item('Individual Compound Product Pages', 'Buying Options', 'Add-to-cart button', 'Add To Cart', 'Large button below quantity choices.', 'shop', 30),
    'compound_product.highlights_eyebrow' => $item('Individual Compound Product Pages', 'Research Details', 'Highlights eyebrow', 'Why Researchers Use It', 'Small label above product highlights.', 'shop', 40),
    'compound_product.highlights_title' => $item('Individual Compound Product Pages', 'Research Details', 'Highlights heading', 'Highlights', 'Large heading above product highlights.', 'shop', 50),
    'compound_product.research_heading' => $item('Individual Compound Product Pages', 'Research Details', 'Research background heading', 'Research Background', 'Heading above the product-specific research background.', 'shop', 60),
    'compound_product.storage_heading' => $item('Individual Compound Product Pages', 'Research Details', 'Storage heading', 'Storage & Handling', 'Heading above product-specific storage wording.', 'shop', 80),
    'compound_product.collections_eyebrow' => $item('Individual Compound Product Pages', 'Related Collections', 'Section eyebrow', 'Bundle & Save', 'Small label above the related research collections heading.', 'shop', 88),
    'compound_product.collections_title' => $item('Individual Compound Product Pages', 'Related Collections', 'Section heading', 'Included In These Protocols', 'Heading above research collections that include this compound.', 'shop', 90),
    'compound_product.collections_description' => $item('Individual Compound Product Pages', 'Related Collections', 'Section description', 'Buying this compound as part of a stack is cheaper than buying it alone, and every stack ships with the bacteriostatic water you need.', 'Paragraph above related research collection cards.', 'shop', 100),
    'compound_product.related_title' => $item('Individual Compound Product Pages', 'Related Products', 'Section heading', 'Other Compounds', 'Heading above other individual compounds.', 'shop', 120),
    'compound_product.trust_1' => $item('Individual Compound Product Pages', 'Buy Box', 'First checkmark line', 'Third-party HPLC tested', 'First checkmark under the add-to-cart button.', 'shop', 130),
    'compound_product.trust_2' => $item('Individual Compound Product Pages', 'Buy Box', 'Second checkmark line', 'Ships within 24 hours', 'Second checkmark under the add-to-cart button.', 'shop', 132),
    'compound_product.trust_3' => $item('Individual Compound Product Pages', 'Buy Box', 'Third checkmark line', 'Lyophilised powder', 'Third checkmark under the add-to-cart button.', 'shop', 134),
    'compound_product.trust_4' => $item('Individual Compound Product Pages', 'Buy Box', 'Fourth checkmark line', 'Free shipping over $200', 'Fourth checkmark under the add-to-cart button. Display text only — the actual free-shipping threshold is configured separately by your developer.', 'shop', 136),

    // Collection-list supporting copy.
    'collections.category_suffix' => $item('Research Collections Page', 'Top Banner', 'Category heading suffix', 'Protocols', 'Word shown after a selected collection category.', 'stacks', 90),
    'collections.item_singular' => $item('Research Collections Page', 'Product List', 'Single-item count word', 'protocol', 'Word shown after the count when one collection is displayed.', 'stacks', 100),
    'collections.item_plural' => $item('Research Collections Page', 'Product List', 'Multiple-item count word', 'protocols', 'Word shown after the count when multiple collections are displayed.', 'stacks', 110),
    'collections.empty_title' => $item('Research Collections Page', 'Empty Results', 'Heading', 'No protocols here', 'Heading shown when a filter has no matching collections.', 'stacks', 120),
    'collections.empty_description' => $item('Research Collections Page', 'Empty Results', 'Description', 'Try a different goal.', 'Short help text when a filter has no matching collections.', 'stacks', 130),
    'collections.empty_button' => $item('Research Collections Page', 'Empty Results', 'Reset button', 'Show All Protocols', 'Button that clears an empty collection filter.', 'stacks', 140),
    'collections.view_button' => $item('Research Collections Page', 'Product List', 'View-item button', 'View Protocol', 'Gold button on every collection row.', 'stacks', 150),
    'collections.cross_sell_title' => $item('Research Collections Page', 'Bottom Call To Action', 'Heading', 'Want To Build Your Own?', 'Heading above the link to individual compounds.', 'stacks', 160),
    'collections.cross_sell_description' => $item('Research Collections Page', 'Bottom Call To Action', 'Description', 'Every compound inside these protocols is available on its own, with quantity-break pricing that drops the unit cost as you scale up.', 'Paragraph above the link to individual compounds.', 'stacks', 170),
    'collections.cross_sell_button' => $item('Research Collections Page', 'Bottom Call To Action', 'Button', 'Shop Individual Compounds', 'Gold button linking to individual compounds.', 'stacks', 180),

    // Account compliance and supporting copy.
    'register.meta_title' => $item('Create Account Page', 'Search & Sharing', 'Browser tab title', 'Create Account — Powered Up Peptides', 'Browser tab title of the create-account page.', 'register', 2),
    'register.introduction' => $item('Create Account Page', 'Top', 'Introduction', 'Track orders, pull batch certificates and reorder your protocol in one click.', 'Paragraph below the Create Account heading.', 'register', 10),
    'login.meta_title' => $item('Sign In Page', 'Search & Sharing', 'Browser tab title', 'Sign In — Powered Up Peptides', 'Browser tab title of the sign-in page.', 'login', 2),
    'login.introduction' => $item('Sign In Page', 'Top', 'Introduction', 'Access your orders, batch certificates and reorder in one click.', 'Paragraph below the Sign In heading.', 'login', 10),
    'login.remember_label' => $item('Sign In Page', 'Form', 'Stay-signed-in label', 'Keep me signed in', 'Label beside the stay-signed-in checkbox.', 'login', 20),
    'shop.meta_title' => $item('Shop Page', 'Search & Sharing', 'Browser tab title', 'Shop Peptides — Powered Up Peptides', 'Browser tab title of the shop page when no category is selected.', 'shop', 2),
    'shop.empty_description' => $item('Shop Page', 'Empty Category', 'Description', 'Try a different category.', 'Text shown when a shop category has no products.', 'shop', 90),
    'register.disclaimer' => $item('Create Account Page', 'Compliance', 'Required confirmation text', 'I am a qualified researcher aged 21 or over and understand these products are supplied strictly for laboratory research use only.', 'Text beside the required research-use checkbox.', 'register', 20),
    'account.meta_title' => $item('Customer Account Page', 'Search & Sharing', 'Browser tab title', 'Your Account — Powered Up Peptides', 'Browser tab title of the customer account page.', 'account', 2),
    'account.empty_orders_description' => $item('Customer Account Page', 'Empty Order History', 'Description', 'Your first protocol is waiting.', 'Text shown when a customer has no orders.', 'account', 10),
];
