<?php

$item = static fn (
    string $page,
    string $section,
    string $label,
    string $default,
    string $locationHint,
    ?string $routeName,
    int $sortOrder,
): array => [
    'page' => $page,
    'section' => $section,
    'label' => $label,
    'default' => $default,
    'location_hint' => $locationHint,
    'route_name' => $routeName,
    'sort_order' => $sortOrder,
];

return [
    // Shared site content.
    'global.meta_description' => $item('Shared Site Content', 'Search & Sharing', 'Default search description', 'Third-party tested research peptides and stack protocols. 99%+ purity, published COA for every batch.', 'Used by search engines and link previews when a page has no custom description.', 'home', 10),
    'global.announcement_title' => $item('Shared Site Content', 'Top Announcement', 'Announcement heading', 'Research Use Only', 'Gold message at the very top of every page.', 'home', 20),
    'global.announcement_detail' => $item('Shared Site Content', 'Top Announcement', 'Announcement details', 'Third-party tested · 99%+ purity · Free shipping over $200', 'Small text beside the gold announcement on larger screens.', 'home', 30),
    'global.nav_shop' => $item('Shared Site Content', 'Main Menu', 'Shop menu item', 'Shop', 'Main navigation on desktop and in the mobile menu.', 'shop', 40),
    'global.nav_collections' => $item('Shared Site Content', 'Main Menu', 'Collections menu item', 'Stacks', 'Main navigation on desktop and in the mobile menu.', 'stacks', 50),
    'global.nav_lab_reports' => $item('Shared Site Content', 'Main Menu', 'Lab reports menu item', 'Lab Reports', 'Main navigation on desktop and in the mobile menu.', 'lab-reports', 60),
    'global.nav_about' => $item('Shared Site Content', 'Main Menu', 'About menu item', 'About Us', 'Main navigation on desktop and in the mobile menu.', 'about', 70),
    'global.nav_contact' => $item('Shared Site Content', 'Main Menu', 'Contact menu item', 'Contact', 'Main navigation on desktop and in the mobile menu.', 'contact', 80),
    'global.footer_description' => $item('Shared Site Content', 'Footer', 'Company description', 'Research-grade peptides with published third-party analysis on every batch. Built for laboratories and researchers who need to trust what is in the vial.', 'Paragraph beside the logo at the bottom of every page.', 'home', 100),
    'global.footer_collections_link' => $item('Shared Site Content', 'Footer', 'Collections link', 'Stack Protocols', 'First link under Shop in the footer.', 'stacks', 110),
    'global.footer_disclaimer_heading' => $item('Shared Site Content', 'Footer Compliance', 'Disclaimer heading', 'RESEARCH USE ONLY.', 'Gold heading in the compliance box at the bottom of every page.', 'home', 120),
    'global.footer_disclaimer' => $item('Shared Site Content', 'Footer Compliance', 'Disclaimer text', 'All products sold by Powered Up Peptides are intended strictly for in-vitro laboratory research and are not for human or veterinary consumption. These products are not drugs, foods, or cosmetics and have not been evaluated by the FDA. Any reference to dosages reflects published third-party literature and is not a recommendation for use in humans. By purchasing, you confirm you are a qualified researcher aged 21 or over.', 'Compliance paragraph at the bottom of every page.', 'home', 130),
    'global.trust_1_title' => $item('Shared Site Content', 'Trust Bar', 'First promise heading', '3rd Party Tested', 'First promise in the four-item trust bar.', 'home', 140),
    'global.trust_1_detail' => $item('Shared Site Content', 'Trust Bar', 'First promise details', 'Every batch, HPLC verified', 'Details below the first trust-bar promise.', 'home', 150),
    'global.trust_2_title' => $item('Shared Site Content', 'Trust Bar', 'Second promise heading', '99%+ Purity', 'Second promise in the four-item trust bar.', 'home', 160),
    'global.trust_2_detail' => $item('Shared Site Content', 'Trust Bar', 'Second promise details', 'Published COA per batch', 'Details below the second trust-bar promise.', 'home', 170),
    'global.trust_3_title' => $item('Shared Site Content', 'Trust Bar', 'Third promise heading', 'Fast Discreet Shipping', 'Third promise in the four-item trust bar.', 'home', 180),
    'global.trust_3_detail' => $item('Shared Site Content', 'Trust Bar', 'Third promise details', 'Ships within 24 hours', 'Details below the third trust-bar promise.', 'home', 190),
    'global.trust_4_title' => $item('Shared Site Content', 'Trust Bar', 'Fourth promise heading', 'Cold Chain Packed', 'Fourth promise in the four-item trust bar.', 'home', 200),
    'global.trust_4_detail' => $item('Shared Site Content', 'Trust Bar', 'Fourth promise details', 'Temperature controlled', 'Details below the fourth trust-bar promise.', 'home', 210),

    // Home page.
    'home.meta_title' => $item('Home Page', 'Search & Sharing', 'Search result title', 'Powered Up Peptides — Research Peptides & Stack Protocols', 'Browser tab, search result, and link-preview title.', 'home', 10),
    'home.hero_eyebrow' => $item('Home Page', 'Top Banner', 'Proof badge', 'Third-Party Tested · 99%+ Purity', 'Small gold badge above the main heading.', 'home', 20),
    'home.hero_title_line_1' => $item('Home Page', 'Top Banner', 'Main heading — first line', 'Power Up Your', 'White first line of the large homepage heading.', 'home', 30),
    'home.hero_title_line_2' => $item('Home Page', 'Top Banner', 'Main heading — gold line', 'Research', 'Gold second line of the large homepage heading.', 'home', 40),
    'home.hero_description' => $item('Home Page', 'Top Banner', 'Introduction', 'Premium research peptides and pre-built stack protocols. Every batch is independently HPLC verified and the certificate of analysis is published before it ships — so you always know exactly what is in the vial.', 'Paragraph below the main homepage heading.', 'home', 50),
    'home.hero_primary_button' => $item('Home Page', 'Top Banner', 'Primary button', 'Shop Stack Protocols', 'Gold button below the homepage introduction.', 'home', 60),
    'home.hero_secondary_button' => $item('Home Page', 'Top Banner', 'Secondary button', 'View Lab Reports', 'Outlined button below the homepage introduction.', 'home', 70),
    'home.collections_eyebrow' => $item('Home Page', 'Collections', 'Section eyebrow', 'Built For Results', 'Small gold text above the collections heading.', 'home', 80),
    'home.collections_title' => $item('Home Page', 'Collections', 'Section heading', 'Stack Protocols', 'Large heading above the collection cards.', 'home', 90),
    'home.collections_description' => $item('Home Page', 'Collections', 'Section description', 'Pre-built systems that pair synergistic compounds with the bacteriostatic water you need. Every stack ships in three protocol tiers — save up to 58% versus buying vials individually.', 'Paragraph above the collection cards.', 'home', 100),
    'home.compounds_eyebrow' => $item('Home Page', 'Individual Compounds', 'Section eyebrow', 'À La Carte', 'Small gold text above the individual compounds heading.', 'home', 110),
    'home.compounds_title' => $item('Home Page', 'Individual Compounds', 'Section heading', 'Individual Compounds', 'Large heading above the individual compound cards.', 'home', 120),
    'home.compounds_description' => $item('Home Page', 'Individual Compounds', 'Section description', 'Building your own protocol? Every compound is available on its own with quantity-break pricing — the more vials, the lower the unit cost.', 'Paragraph above the individual compound cards.', 'home', 130),
    'home.why_eyebrow' => $item('Home Page', 'Why Powered Up', 'Section eyebrow', 'Why Powered Up', 'Small gold text above the trust section.', 'home', 140),
    'home.why_title' => $item('Home Page', 'Why Powered Up', 'Section heading', 'No Guessing. Ever.', 'Large heading above the three trust cards.', 'home', 150),
    'home.why_description' => $item('Home Page', 'Why Powered Up', 'Section description', 'Most suppliers ask you to take their word for it. We publish the receipts.', 'Short paragraph above the three trust cards.', 'home', 160),
    'home.closing_title' => $item('Home Page', 'Bottom Call To Action', 'Heading', 'Ready To Power Up?', 'Large heading near the bottom of the homepage.', 'home', 170),
    'home.closing_description' => $item('Home Page', 'Bottom Call To Action', 'Description', 'Start with a stack protocol built around your research goal, or browse the full compound library and build your own.', 'Paragraph in the bottom call-to-action box.', 'home', 180),
    'home.closing_primary_button' => $item('Home Page', 'Bottom Call To Action', 'Primary button', 'Shop Stack Protocols', 'Gold button in the bottom call-to-action box.', 'home', 190),

    // Shop page.
    'shop.meta_description' => $item('Shop Page', 'Search & Sharing', 'Search description', 'Individual research peptides with published third-party analysis and quantity-break pricing on every vial.', 'Search result and link-preview description for the Shop page.', 'shop', 10),
    'shop.hero_eyebrow' => $item('Shop Page', 'Top Banner', 'Eyebrow', 'Individual Compounds', 'Small gold heading at the top of the Shop page.', 'shop', 20),
    'shop.hero_title' => $item('Shop Page', 'Top Banner', 'Main heading', 'Shop Compounds', 'Large heading when no product category is selected.', 'shop', 30),
    'shop.hero_description' => $item('Shop Page', 'Top Banner', 'Introduction', 'Single vials for researchers building their own protocol. Every compound is third-party tested with the certificate published against its batch number, and unit prices drop automatically as quantity goes up.', 'Paragraph under the Shop page heading.', 'shop', 40),
    'shop.collections_link' => $item('Shop Page', 'Top Banner', 'Collections link', 'Looking for complete protocols? Browse stacks →', 'Gold link below the Shop introduction.', 'shop', 50),
    'shop.cross_sell_title' => $item('Shop Page', 'Bottom Call To Action', 'Heading', 'Rather Not Build It Yourself?', 'Large heading in the bottom collection callout.', 'shop', 60),
    'shop.cross_sell_description' => $item('Shop Page', 'Bottom Call To Action', 'Description', 'Our stack protocols pair these compounds into complete programmes with a set supply length, so you do not have to work out the combination.', 'Paragraph in the bottom collection callout.', 'shop', 70),
    'shop.cross_sell_button' => $item('Shop Page', 'Bottom Call To Action', 'Button', 'View Stack Protocols', 'Gold button in the bottom collection callout.', 'shop', 80),

    // Research collections page (currently /stacks).
    'collections.meta_title' => $item('Research Collections Page', 'Search & Sharing', 'Search result title', 'Stack Protocols — Powered Up Peptides', 'Browser tab, search result, and link-preview title when no category is selected.', 'stacks', 10),
    'collections.meta_description' => $item('Research Collections Page', 'Search & Sharing', 'Search description', 'Complete research peptide protocols. Each stack pairs proven compounds into a programme with a set supply length and published lab results.', 'Search result and link-preview description.', 'stacks', 20),
    'collections.breadcrumb' => $item('Research Collections Page', 'Top Banner', 'Breadcrumb label', 'Stacks', 'Small page name beside Home at the top.', 'stacks', 30),
    'collections.hero_eyebrow' => $item('Research Collections Page', 'Top Banner', 'Eyebrow', 'Complete Protocols', 'Small gold heading above the main page title.', 'stacks', 40),
    'collections.hero_title' => $item('Research Collections Page', 'Top Banner', 'Main heading', 'Stack Protocols', 'Large title in the page banner when no category is selected.', 'stacks', 50),
    'collections.hero_description' => $item('Research Collections Page', 'Top Banner', 'Introduction', 'Every stack pairs compounds that work together into one programme, with a fixed supply length and a single price. Pick the goal, pick the duration, and everything arrives in one cold chain shipment.', 'Paragraph below the main page title.', 'stacks', 60),
    'collections.shop_link' => $item('Research Collections Page', 'Top Banner', 'Single-vials link', 'Prefer single vials? Shop compounds →', 'Gold link below the introduction.', 'stacks', 70),
    'collections.all_filter' => $item('Research Collections Page', 'Product List', 'All-items filter', 'All Protocols', 'First filter button above the collection cards.', 'stacks', 80),

    // Lab reports page.
    'labs.meta_title' => $item('Lab Reports Page', 'Search & Sharing', 'Search result title', 'Lab Reports & Certificates of Analysis — Powered Up Peptides', 'Browser tab, search result, and link-preview title.', 'lab-reports', 10),
    'labs.hero_title' => $item('Lab Reports Page', 'Top Banner', 'Main heading', 'Lab Reports', 'Large title at the top of the page.', 'lab-reports', 20),
    'labs.hero_description' => $item('Lab Reports Page', 'Top Banner', 'Introduction', 'Every batch we sell is tested by an independent, accredited laboratory using HPLC and mass spectrometry before it goes on sale. Look up any batch number printed on your vial to see its certificate of analysis.', 'Paragraph under the main page heading.', 'lab-reports', 30),
    'labs.search_placeholder' => $item('Lab Reports Page', 'Batch Search', 'Search box placeholder', 'Enter batch number or product name', 'Faint instruction inside the batch search box.', 'lab-reports', 40),
    'labs.search_button' => $item('Lab Reports Page', 'Batch Search', 'Search button', 'Look Up', 'Gold button beside the batch search box.', 'lab-reports', 50),
    'labs.pending_label' => $item('Lab Reports Page', 'Reports Table', 'Missing-PDF label', 'Pending Upload', 'Shown when a certificate PDF has not been attached.', 'lab-reports', 60),
    'labs.table_note' => $item('Lab Reports Page', 'Reports Table', 'Note below reports', 'Certificate PDFs are attached per batch in the admin. Rows marked “pending upload” have been tested and released, but the signed PDF has not been attached to this record yet. The certificates currently linked here are sample documents containing placeholder data, not real laboratory results.', 'Small explanatory note directly below the reports table.', 'lab-reports', 70),

    // About page.
    'about.meta_description' => $item('About Page', 'Search & Sharing', 'Search description', 'Who we are, how we source and test our research peptides, and the standards every batch has to clear before it ships.', 'Search result and link-preview description.', 'about', 10),
    'about.hero_eyebrow' => $item('About Page', 'Top Banner', 'Eyebrow', 'Our Standard', 'Small gold heading above the main title.', 'about', 20),
    'about.hero_title' => $item('About Page', 'Top Banner', 'Main heading', 'Know Exactly What Is In The Vial', 'Large heading at the top of the About page.', 'about', 30),
    'about.hero_description' => $item('About Page', 'Top Banner', 'Introduction', 'Powered Up Peptides exists because too much of this market asks researchers to take purity on faith. We publish the analysis for every batch we sell, so you never have to.', 'Paragraph below the main About heading.', 'about', 40),
    'about.story_eyebrow' => $item('About Page', 'Our Story', 'Eyebrow', 'Why We Started', 'Small gold heading above the company story.', 'about', 50),
    'about.story_title' => $item('About Page', 'Our Story', 'Heading', 'Built Out Of Frustration', 'Large heading above the company story.', 'about', 60),
    'about.story_paragraph_1' => $item('About Page', 'Our Story', 'First paragraph', 'Anyone who has sourced research peptides knows the routine. A vendor claims 99% purity. There is no certificate, or there is one certificate from two years ago covering a batch you did not receive. You are left running your own verification before you can even begin the work you actually planned.', 'First paragraph in the Why We Started section.', 'about', 70),
    'about.story_paragraph_2' => $item('About Page', 'Our Story', 'Second paragraph', 'We built Powered Up Peptides around the opposite default. Every batch is sent to an independent lab for HPLC and mass spectrometry analysis before it is listed. That report is published against the batch number printed on your vial, and it stays public whether the result flatters us or not.', 'Second paragraph in the Why We Started section.', 'about', 80),
    'about.story_paragraph_3' => $item('About Page', 'Our Story', 'Third paragraph', 'If a batch does not clear our purity threshold, it does not get sold. It is a simple rule, and it is the entire reason this company exists.', 'Third paragraph in the Why We Started section.', 'about', 90),
    'about.compliance_eyebrow' => $item('About Page', 'Compliance', 'Eyebrow', 'Where We Draw The Line', 'Small gold heading above the compliance statement.', 'about', 100),
    'about.compliance_title' => $item('About Page', 'Compliance', 'Heading', 'Research Use Only', 'Large heading above the compliance statement.', 'about', 110),
    'about.compliance_paragraph_1' => $item('About Page', 'Compliance', 'First paragraph', 'Everything we sell is supplied strictly for in-vitro laboratory research. Our products are not drugs, foods or cosmetics, they have not been evaluated by the FDA, and they are not for human or veterinary consumption.', 'First paragraph in the compliance box.', 'about', 120),
    'about.compliance_paragraph_2' => $item('About Page', 'Compliance', 'Second paragraph', 'We do not provide dosing protocols, medical guidance or advice on administration, and we will not do so if asked. Where our product pages cite figures from published literature, that is a reference to the research record, not a recommendation.', 'Second paragraph in the compliance box.', 'about', 130),
    'about.compliance_paragraph_3' => $item('About Page', 'Compliance', 'Third paragraph', 'By ordering, you confirm you are a qualified researcher aged 21 or over and that you are responsible for compliance with the regulations that apply where you are.', 'Final paragraph in the compliance box.', 'about', 140),

    // Contact page.
    'contact.meta_description' => $item('Contact Page', 'Search & Sharing', 'Search description', 'Questions about an order, a protocol or a batch certificate? Talk to the Powered Up Peptides team.', 'Search result and link-preview description.', 'contact', 10),
    'contact.hero_title' => $item('Contact Page', 'Top Banner', 'Main heading', 'Talk To Us', 'Large heading at the top of the Contact page.', 'contact', 20),
    'contact.hero_description' => $item('Contact Page', 'Top Banner', 'Introduction', 'Order issues, batch certificates, protocol questions or bulk enquiries — a real person reads every message and replies within one business day.', 'Paragraph below the main Contact heading.', 'contact', 30),
    'contact.form_disclaimer' => $item('Contact Page', 'Message Form', 'Advice disclaimer', 'We cannot provide dosing, medical or veterinary advice. All products are supplied strictly for laboratory research use.', 'Small compliance note below the Send Message button.', 'contact', 40),
    'contact.protocol_help_title' => $item('Contact Page', 'Faster Answers', 'Collection-help link heading', 'Not sure which protocol?', 'Third shortcut card in the Faster Answers box.', 'contact', 50),
    'contact.protocol_help_description' => $item('Contact Page', 'Faster Answers', 'Collection-help link description', 'Every stack lists its goal, components and supply length.', 'Description in the third Faster Answers shortcut card.', 'contact', 60),

    // Cart and checkout compliance text.
    'cart.empty_description' => $item('Cart Page', 'Empty Cart', 'Empty-cart description', 'Start with a stack protocol built around your research goal, or browse the compound library and build your own.', 'Paragraph shown when the shopping cart is empty.', 'cart', 10),
    'cart.empty_collections_button' => $item('Cart Page', 'Empty Cart', 'Collections button', 'Shop Stack Protocols', 'Gold button shown when the shopping cart is empty.', 'cart', 20),
    'cart.disclaimer_heading' => $item('Cart Page', 'Checkout Disclaimer', 'Disclaimer heading', 'Research-use disclaimer', 'Gold heading above the required acceptance checkbox.', 'cart', 30),
    'cart.disclaimer_text' => $item('Cart Page', 'Checkout Disclaimer', 'Required acceptance text', 'I confirm that I am a qualified researcher aged 21 or over and that these products are strictly for in-vitro laboratory research only. They are not for human or veterinary consumption, diagnostic use, or therapeutic use.', 'Text beside the required checkbox before checkout.', 'cart', 40),
    'cart.disclaimer_button' => $item('Cart Page', 'Checkout Disclaimer', 'Proceed button', 'Accept & Proceed To Checkout', 'Checkout button directly below the required disclaimer.', 'cart', 50),
    'checkout.disclaimer_text' => $item('Checkout Page', 'Compliance', 'Final confirmation text', 'I confirm I am a qualified researcher aged 21 or over, and that these products will be used strictly for in-vitro laboratory research. They are not for human or veterinary consumption, and not for diagnostic or therapeutic use.', 'Text beside the compliance checkbox on checkout.', 'checkout', 10),

    // Text shared by all research-collection product pages.
    'collection_product.breadcrumb' => $item('Research Collection Product Pages', 'Top Banner', 'Collections breadcrumb', 'Stack Protocols', 'Small link between Home and the product name.', 'stacks', 10),
    'collection_product.choose_heading' => $item('Research Collection Product Pages', 'Buying Options', 'Option selector heading', 'Choose Your Protocol', 'Heading immediately above the collection options.', 'stacks', 20),
    'collection_product.choose_help' => $item('Research Collection Product Pages', 'Buying Options', 'Option selector help', 'Longer supply = lower cost per vial', 'Small help text beside the option selector heading.', 'stacks', 30),
    'collection_product.add_button' => $item('Research Collection Product Pages', 'Buying Options', 'Add-to-cart button', 'Add Protocol To Cart', 'Large button below the collection options.', 'stacks', 40),
    'collection_product.included_eyebrow' => $item('Research Collection Product Pages', 'What Is Included', 'Section eyebrow', 'Inside The Box', 'Small label above the included-items heading.', 'stacks', 50),
    'collection_product.included_title' => $item('Research Collection Product Pages', 'What Is Included', 'Section heading', 'What’s Included', 'Large heading above the included-items table.', 'stacks', 60),
    'collection_product.included_description' => $item('Research Collection Product Pages', 'What Is Included', 'Section description', 'Vial counts below are shown per protocol tier. Every tier includes the bacteriostatic water required to reconstitute the full protocol.', 'Paragraph above the included-items table.', 'stacks', 70),
    'collection_product.table_compound_heading' => $item('Research Collection Product Pages', 'What Is Included', 'Table heading — item column', 'Compound', 'First column heading of the included-items table.', 'stacks', 72),
    'collection_product.table_details_heading' => $item('Research Collection Product Pages', 'What Is Included', 'Table heading — details column', 'Product Details', 'Second column heading of the included-items table.', 'stacks', 74),
    'collection_product.compounds_eyebrow' => $item('Research Collection Product Pages', 'Included Compounds', 'Section eyebrow', 'The Compounds', 'Small label above the included compound cards.', 'stacks', 120),
    'collection_product.compounds_title' => $item('Research Collection Product Pages', 'Included Compounds', 'Section heading', 'Every Vial, Documented', 'Large heading above the included compound cards.', 'stacks', 130),
    'collection_product.compounds_description' => $item('Research Collection Product Pages', 'Included Compounds', 'Section description', 'Each compound in this protocol has its own product page with research background, storage guidance, and the batch certificate of analysis.', 'Paragraph above the included compound cards.', 'stacks', 140),
    'collection_product.lab_eyebrow' => $item('Research Collection Product Pages', 'Lab Results', 'Section eyebrow', 'Transparency', 'Small label above the batch lab results heading.', 'stacks', 145),
    'collection_product.lab_title' => $item('Research Collection Product Pages', 'Lab Results', 'Section heading', 'Batch Lab Results', 'Large heading above the batch results table. The last two words are shown in the accent colour.', 'stacks', 148),
    'collection_product.lab_description' => $item('Research Collection Product Pages', 'Lab Results', 'Section description', 'Independent third-party analysis for the exact batches included in this protocol.', 'Paragraph above product-level batch results.', 'stacks', 150),
    'collection_product.other_title' => $item('Research Collection Product Pages', 'Related Collections', 'Section heading', 'Other Protocols', 'Heading above other research collection cards.', 'stacks', 160),

    // Text shared by all individual compound product pages.
    'compound_product.quantity_heading' => $item('Individual Compound Product Pages', 'Buying Options', 'Quantity selector heading', 'Choose Quantity', 'Heading immediately above quantity choices.', 'shop', 10),
    'compound_product.quantity_help' => $item('Individual Compound Product Pages', 'Buying Options', 'Quantity selector help', 'Unit price drops with volume', 'Small help text beside the quantity selector heading.', 'shop', 20),
    'compound_product.add_button' => $item('Individual Compound Product Pages', 'Buying Options', 'Add-to-cart button', 'Add To Cart', 'Large button below quantity choices.', 'shop', 30),
    'compound_product.highlights_eyebrow' => $item('Individual Compound Product Pages', 'Research Details', 'Highlights eyebrow', 'Why Researchers Use It', 'Small label above product highlights.', 'shop', 40),
    'compound_product.highlights_title' => $item('Individual Compound Product Pages', 'Research Details', 'Highlights heading', 'Highlights', 'Large heading above product highlights.', 'shop', 50),
    'compound_product.research_heading' => $item('Individual Compound Product Pages', 'Research Details', 'Research background heading', 'Research Background', 'Heading above the product-specific research background.', 'shop', 60),
    'compound_product.storage_heading' => $item('Individual Compound Product Pages', 'Research Details', 'Storage heading', 'Storage & Handling', 'Heading above product-specific storage wording.', 'shop', 80),
    'compound_product.collections_eyebrow' => $item('Individual Compound Product Pages', 'Related Collections', 'Section eyebrow', 'Bundle & Save', 'Small label above the related research collections heading.', 'shop', 88),
    'compound_product.collections_title' => $item('Individual Compound Product Pages', 'Related Collections', 'Section heading', 'Included In These Protocols', 'Heading above research collections that include this compound.', 'shop', 90),
    'compound_product.collections_description' => $item('Individual Compound Product Pages', 'Related Collections', 'Section description', 'Buying this compound as part of a stack is cheaper than buying it alone, and every stack ships with the bacteriostatic water you need.', 'Paragraph above related research collection cards.', 'shop', 100),
    'compound_product.faq_title' => $item('Individual Compound Product Pages', 'Questions', 'FAQ heading', 'Frequently Asked', 'Heading above product-specific questions and answers.', 'shop', 110),
    'compound_product.related_title' => $item('Individual Compound Product Pages', 'Related Products', 'Section heading', 'Other Compounds', 'Heading above other individual compounds.', 'shop', 120),

    // Collection-list supporting copy.
    'collections.category_suffix' => $item('Research Collections Page', 'Top Banner', 'Category heading suffix', 'Protocols', 'Word shown after a selected collection category.', 'stacks', 90),
    'collections.item_singular' => $item('Research Collections Page', 'Product List', 'Single-item count word', 'protocol', 'Word shown after the count when one collection is displayed.', 'stacks', 100),
    'collections.item_plural' => $item('Research Collections Page', 'Product List', 'Multiple-item count word', 'protocols', 'Word shown after the count when multiple collections are displayed.', 'stacks', 110),
    'collections.empty_title' => $item('Research Collections Page', 'Empty Results', 'Heading', 'No protocols here', 'Heading shown when a filter has no matching collections.', 'stacks', 120),
    'collections.empty_description' => $item('Research Collections Page', 'Empty Results', 'Description', 'Try a different goal.', 'Short help text when a filter has no matching collections.', 'stacks', 130),
    'collections.empty_button' => $item('Research Collections Page', 'Empty Results', 'Reset button', 'Show All Protocols', 'Button that clears an empty collection filter.', 'stacks', 140),
    'collections.view_button' => $item('Research Collections Page', 'Product List', 'View-item button', 'View Protocol', 'Gold button on every collection row.', 'stacks', 150),
    'collections.cross_sell_title' => $item('Research Collections Page', 'Bottom Call To Action', 'Heading', 'Want To Build Your Own?', 'Heading above the link to individual compounds.', 'stacks', 160),
    'collections.cross_sell_description' => $item('Research Collections Page', 'Bottom Call To Action', 'Description', 'Every compound inside these protocols is available on its own, with quantity-break pricing that drops the unit cost as you scale up.', 'Paragraph above the link to individual compounds.', 'stacks', 170),
    'collections.cross_sell_button' => $item('Research Collections Page', 'Bottom Call To Action', 'Button', 'Shop Individual Compounds', 'Gold button linking to individual compounds.', 'stacks', 180),

    // Account compliance and supporting copy.
    'register.introduction' => $item('Create Account Page', 'Top', 'Introduction', 'Track orders, pull batch certificates and reorder your protocol in one click.', 'Paragraph below the Create Account heading.', 'register', 10),
    'register.disclaimer' => $item('Create Account Page', 'Compliance', 'Required confirmation text', 'I am a qualified researcher aged 21 or over and understand these products are supplied strictly for laboratory research use only.', 'Text beside the required research-use checkbox.', 'register', 20),
    'account.empty_orders_description' => $item('Customer Account Page', 'Empty Order History', 'Description', 'Your first protocol is waiting.', 'Text shown when a customer has no orders.', 'account', 10),
];
